

- name: set var nginx user account for Redhat
  set_fact:
    nginx_uid: "nginx"
    nginx_gid: "nginx"
  when: ansible_os_family == "RedHat"

- name: set var nginx user account for Debian
  set_fact:
    nginx_uid: "www-data"
    nginx_gid: "www-data"
  when: ansible_os_family == "Debian"


- name: Install the selinux python module
  yum: name=libselinux-python state=present
  when: ansible_os_family == "RedHat"

- name: Copy the epel packages
  copy: src=epel.repo dest=/etc/yum.repos.d/epel_ansible.repo
  when: ansible_os_family == "RedHat"

- name: Install the nginx packages
  yum: name={{ item }} state=present
  with_items: "{{redhat_pkg}}"
  when: ansible_os_family == "RedHat"

- name: Install the nginx packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ubuntu_pkg}}"
  environment: '{{ env }}'
  when: ansible_os_family == "Debian"

- name: Install the certbot packages
  apt: name=certbot state=present update_cache=yes default_release=jessie-backports
  environment: '{{ env }}'
  when: ansible_os_family == "Debian"

- name: Create the directories for site specific configurations and ssl keys
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "ssl"



- name: Check if /etc/nginx/nginx.conf exists
  stat: path=/etc/nginx/nginx.conf
  register: nginx_conf_exists

- name: Copy the nginx configuration file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  when: (nginx_create_nginx_conf is defined and nginx_create_nginx_conf|lower == "true") or nginx_conf_exists is not defined
  notify:
   - restart nginx

- name: create directory /srv/www/letsencrypt/
  file: path=/srv/www/letsencrypt/{{item.file_name}} state=directory
  with_items:
    - "{{ nginx_sites }}"

- name: Delete the links to delete site configurations for letsencrypt
  file: path=/etc/nginx/sites-enabled/{{ item.file_name }} state=absent src=/etc/nginx/sites-available/{{ item.file_name }}
  with_items: "{{nginx_sites}}"

- name: Create the configurations for sites
  template: src=site_letsencrypt.j2 dest=/etc/nginx/sites-available/{{ item.file_name }}
  with_items:
    - "{{nginx_sites}}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"

- name: Create the links to enable site configurations for letsencrypt
  file: path=/etc/nginx/sites-enabled/{{ item.file_name }} state=link src=/etc/nginx/sites-available/{{ item.file_name }}
  with_items:
    - "{{nginx_sites}}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"

- name: reload nginx
  service: name=nginx state=reloaded
  with_items:
    - "{{nginx_sites}}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"

- name: configure certbot webroot plugin
  command: certbot certonly -n --expand --webroot -w "/srv/www/letsencrypt/{{item.file_name}}" -d "{{item.ssl.domains|join(',')}}" --cert-name "{{ item.file_name }}"
  with_items:
    - "{{nginx_sites}}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"

- name: Copy SSL keys
  copy: src={{ item.ssl.local_keystore_dir }}/{{item.ssl.key }} dest={{ nginx_ssl_dir }}/{{ item.ssl.key }}  owner={{ nginx_uid }} group={{ nginx_gid }} mode=400 backup=no
  with_items:
    - "{{nginx_sites }}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.key is defined
    - item.ssl.key != None
    - item.ssl.supplier == "local"

- name: Copy SSL certificates
  copy: src={{ item.ssl.local_keystore_dir }}/{{item.ssl.certificate }} dest={{ nginx_ssl_dir }}/{{ item.ssl.certificate }}  owner={{ nginx_uid }} group={{ nginx_gid }} mode=644 backup=no
  with_items:
    - "{{nginx_sites }}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.certificate is defined
    - item.ssl.certificate != None
    - item.ssl.supplier == "local"

- name: Copy the nginx default configuration file
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Copy the nginx default site configuration file
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: Create the link for site enabled specific configurations
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default

- name: Create the configurations for sites
  template: src=site.j2 dest=/etc/nginx/sites-available/{{ item.file_name }}
  with_items: "{{nginx_sites}}"


- name: Create the links to enable site configurations
  file: path=/etc/nginx/sites-enabled/{{ item.file_name }} state=link src=/etc/nginx/sites-available/{{ item.file_name }}
  with_items: "{{nginx_sites}}"
  notify:
   - reload nginx


- name: start the nginx service
  service: name=nginx state=started enabled=yes
